import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() =>
      ['en', 'pt', 'es', 'zh_Hans', 'zh_Hant', 'ja'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? ptText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? zh_HantText = '',
    String? jaText = '',
  }) =>
      [
        enText,
        ptText,
        esText,
        zh_HansText,
        zh_HantText,
        jaText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // login
  {
    '2l6glm7g': {
      'en': 'Welcome Back,',
      'es': 'Bienvenido de nuevo,',
      'ja': 'おかえり、',
      'pt': 'Bem vindo de volta,',
      'zh_Hans': '欢迎回来，',
      'zh_Hant': '歡迎回來，',
    },
    '2s1rbpjf': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'ja': '電子メールアドレス',
      'pt': 'Endereço de email',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    '910mncym': {
      'en': 'Enter your email here...',
      'es': 'Introduce tu email aquí...',
      'ja': 'ここにメールアドレスを入力してください...',
      'pt': 'Insira seu e-mail aqui...',
      'zh_Hans': '在此输入您的电子邮件...',
      'zh_Hant': '在此輸入您的電子郵件...',
    },
    '6olntars': {
      'en': 'Password',
      'es': 'Contraseña',
      'ja': 'パスワード',
      'pt': 'Senha',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'yfhbigqc': {
      'en': 'Enter your email here...',
      'es': 'Introduce tu email aquí...',
      'ja': 'ここにメールアドレスを入力してください...',
      'pt': 'Insira seu e-mail aqui...',
      'zh_Hans': '在此输入您的电子邮件...',
      'zh_Hant': '在此輸入您的電子郵件...',
    },
    '3mnohnp5': {
      'en': 'Forgot Password?',
      'es': '¿Has olvidado tu contraseña?',
      'ja': 'パスワードをお忘れですか？',
      'pt': 'Esqueceu sua senha?',
      'zh_Hans': '忘记密码？',
      'zh_Hant': '忘記密碼？',
    },
    'v2o07n0s': {
      'en': 'Login',
      'es': 'Acceso',
      'ja': 'ログイン',
      'pt': 'Conecte-se',
      'zh_Hans': '登录',
      'zh_Hant': '登入',
    },
    'lc8ynk7x': {
      'en': 'Don\'t have an account?',
      'es': '¿No tienes una cuenta?',
      'ja': 'アカウントをお持ちではありませんか?',
      'pt': 'Não tem uma conta?',
      'zh_Hans': '沒有帳戶？',
      'zh_Hant': '沒有帳戶？',
    },
    'wre3r4s8': {
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
      'zh_Hans': '创建账户',
      'zh_Hant': '建立帳戶',
    },
    'qtag23jn': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // createAccount
  {
    '2uomtpv7': {
      'en': 'Get Started Below,',
      'es': 'Comience a continuación.',
      'ja': '下記から始めましょう。',
      'pt': 'Comece abaixo,',
      'zh_Hans': '从下面开始，',
      'zh_Hant': '從下面開始，',
    },
    'yvn36o85': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'ja': '電子メールアドレス',
      'pt': 'Endereço de email',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    '2yl8mink': {
      'en': 'Enter your email here...',
      'es': 'Introduce tu email aquí...',
      'ja': 'ここにメールアドレスを入力してください...',
      'pt': 'Insira seu e-mail aqui...',
      'zh_Hans': '在此输入您的电子邮件...',
      'zh_Hant': '在此輸入您的電子郵件...',
    },
    'ndrowql5': {
      'en': 'Password',
      'es': 'Contraseña',
      'ja': 'パスワード',
      'pt': 'Senha',
      'zh_Hans': '密码',
      'zh_Hant': '密碼',
    },
    'ag0qvbt5': {
      'en': 'Enter your email here...',
      'es': 'Introduce tu email aquí...',
      'ja': 'ここにメールアドレスを入力してください...',
      'pt': 'Insira seu e-mail aqui...',
      'zh_Hans': '在此输入您的电子邮件...',
      'zh_Hant': '在此輸入您的電子郵件...',
    },
    'yu4igd0b': {
      'en': 'Create Account',
      'es': 'Crear una cuenta',
      'ja': 'アカウントを作成する',
      'pt': 'Criar uma conta',
      'zh_Hans': '创建账户',
      'zh_Hant': '建立帳戶',
    },
    '8p12svsn': {
      'en': 'Already have an account?',
      'es': '¿Ya tienes una cuenta?',
      'ja': 'すでにアカウントをお持ちですか?',
      'pt': 'Já tem uma conta?',
      'zh_Hans': '已有账户？',
      'zh_Hant': '已經有帳戶？',
    },
    'iran5ad7': {
      'en': 'Login',
      'es': 'Acceso',
      'ja': 'ログイン',
      'pt': 'Conecte-se',
      'zh_Hans': '登录',
      'zh_Hant': '登入',
    },
    'm9gvr7ay': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // homePage_MAIN
  {
    'rdpc7bw4': {
      'en': 'Welcome!',
      'es': '¡Bienvenido!',
      'ja': 'いらっしゃいませ！',
      'pt': 'Bem-vindo!',
      'zh_Hans': '欢迎！',
      'zh_Hant': '歡迎！',
    },
    'v184zzck': {
      'en': 'Find your Dream Space To Getaway',
      'es': 'Encuentra el espacio de tus sueños para escaparte',
      'ja': '夢の逃避場所を見つけよう',
      'pt': 'Encontre o espaço dos seus sonhos para uma escapadela',
      'zh_Hans': '找到您梦想的度假空间',
      'zh_Hant': '尋找您夢想的度假空間',
    },
    '0jvh09dh': {
      'en': 'Address, city, state...',
      'es': 'Dirección, ciudad, estado...',
      'ja': '住所、市、州...',
      'pt': 'Endereço, cidade, estado...',
      'zh_Hans': '地址、城市、州...',
      'zh_Hant': '地址、城市、州...',
    },
    '9cwhqs9q': {
      'en': 'Search',
      'es': 'Buscar',
      'ja': '検索',
      'pt': 'Procurar',
      'zh_Hans': '搜索',
      'zh_Hant': '搜尋',
    },
    '855g1pvo': {
      'en': 'Rating',
      'es': 'Clasificación',
      'ja': '評価',
      'pt': 'Avaliação',
      'zh_Hans': '等级',
      'zh_Hant': '等級',
    },
    'q2ouqh3g': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // propertyDetails
  {
    '4996r9vf': {
      'en': 'Reviews',
      'es': 'Reseñas',
      'ja': 'レビュー',
      'pt': 'Avaliações',
      'zh_Hans': '评论',
      'zh_Hant': '評論',
    },
    'z6tngtgx': {
      'en': 'DESCRIPTION',
      'es': 'DESCRIPCIÓN',
      'ja': '説明',
      'pt': 'DESCRIÇÃO',
      'zh_Hans': '描述',
      'zh_Hant': '描述',
    },
    'jkro07zg': {
      'en': 'Amenities',
      'es': 'Comodidades',
      'ja': 'アメニティ',
      'pt': 'Comodidades',
      'zh_Hans': '便利设施',
      'zh_Hant': '便利設施',
    },
    'x0s0vd72': {
      'en': 'What people are saying',
      'es': 'Lo que la gente está diciendo',
      'ja': '人々が言っていること',
      'pt': 'O que as pessoas estão dizendo',
      'zh_Hans': '人们在说什么',
      'zh_Hant': '人們在說什麼',
    },
    'vr4h7guw': {
      'en': 'Josh Richardson',
      'es': 'Josh Richardson',
      'ja': 'ジョシュ・リチャードソン',
      'pt': 'Josh Richardson',
      'zh_Hans': '乔希·理查德森',
      'zh_Hant': '喬許·理查森',
    },
    'syw8mfmj': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'es':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'ja':
          'ロレム・イプサム・ドルー・シット・アメット、コンセクト・アディピシング・エリート、セド・ド・エイウスモッド・テンポラ・インシディダント・ユー・レイバーとドローレ・マグナ・アリクア。最低限のお金は必要です...',
      'pt':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidente ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'zh_Hans':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可爱的小兔子图片大全 可爱的小兔子设计素材 可爱的兔子模板下载 可爱...',
      'zh_Hant':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可愛的小兔子圖片大全 可愛的小兔子設計素材 可愛的兔子模板下載 可愛...',
    },
    'n5xw7soj': {
      'en': 'Josh Richardson',
      'es': 'Josh Richardson',
      'ja': 'ジョシュ・リチャードソン',
      'pt': 'Josh Richardson',
      'zh_Hans': '乔希·理查德森',
      'zh_Hant': '喬許·理查森',
    },
    'nge5dqvu': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'es':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'ja':
          'ロレム・イプサム・ドルー・シット・アメット、コンセクト・アディピシング・エリート、セド・ド・エイウスモッド・テンポラ・インシディダント・ユー・レイバーとドローレ・マグナ・アリクア。最低限のお金は必要です...',
      'pt':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidente ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'zh_Hans':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可爱的小兔子图片大全 可爱的小兔子设计素材 可爱的兔子模板下载 可爱...',
      'zh_Hant':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可愛的小兔子向量素材下載 非凡圖庫...',
    },
    '3kgkh4e2': {
      'en': '\$156',
      'es': '\$156',
      'ja': '156ドル',
      'pt': '\$ 156',
      'zh_Hans': '\$156',
      'zh_Hant': '156 美元',
    },
    'ss4bbv14': {
      'en': '+ taxes/fees',
      'es': '+ impuestos/tarifas',
      'ja': '+ 税金/手数料',
      'pt': '+ impostos/taxas',
      'zh_Hans': '+ 税费',
      'zh_Hant': '+ 稅金/費用',
    },
    '42mg1c5p': {
      'en': 'per night',
      'es': 'por noche',
      'ja': '1泊あたり',
      'pt': 'por noite',
      'zh_Hans': '每晚',
      'zh_Hant': '每晚',
    },
    '1goeutxg': {
      'en': 'Book Now',
      'es': 'Reservar ahora',
      'ja': '今すぐ予約',
      'pt': 'Reserve agora',
      'zh_Hans': '立即预订',
      'zh_Hant': '立即預訂',
    },
    'uax48vbu': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // searchProperties
  {
    '6okb67wj': {
      'en': 'Search',
      'es': 'Buscar',
      'ja': '検索',
      'pt': 'Procurar',
      'zh_Hans': '搜索',
      'zh_Hant': '搜尋',
    },
    'ctt5imjr': {
      'en': 'Address, city, state...',
      'es': 'Dirección, ciudad, estado...',
      'ja': '住所、市、州...',
      'pt': 'Endereço, cidade, estado...',
      'zh_Hans': '地址、城市、州...',
      'zh_Hant': '地址、城市、州...',
    },
    'htkj7c2z': {
      'en': 'Search',
      'es': 'Buscar',
      'ja': '検索',
      'pt': 'Procurar',
      'zh_Hans': '搜索',
      'zh_Hant': '搜尋',
    },
    'kc8rx232': {
      'en': 'Rating',
      'es': 'Clasificación',
      'ja': '評価',
      'pt': 'Avaliação',
      'zh_Hans': '等级',
      'zh_Hant': '等級',
    },
    'xf3lvvvn': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // myTrips
  {
    'el4zoc74': {
      'en': 'Upcoming',
      'es': 'Próximamente',
      'ja': '今後の予定',
      'pt': 'Por vir',
      'zh_Hans': '即将推出',
      'zh_Hant': '即將推出',
    },
    'mwox8xy5': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    'fyupa1lu': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'xydxzohv': {
      'en': 'Completed',
      'es': 'Terminado',
      'ja': '完了',
      'pt': 'Concluído',
      'zh_Hans': '完全的',
      'zh_Hant': '完全的',
    },
    'ajhpjjyq': {
      'en': 'Cancelled',
      'es': 'Cancelado',
      'ja': 'キャンセル',
      'pt': 'Cancelado',
      'zh_Hans': '取消',
      'zh_Hant': '取消',
    },
    'h1584afz': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    '9u0whyxx': {
      'en': 'Rate Trip',
      'es': 'Tarifa de viaje',
      'ja': '旅行を評価する',
      'pt': 'Taxa de viagem',
      'zh_Hans': '评价行程',
      'zh_Hant': '行程價格',
    },
    'esrskqs4': {
      'en': 'Locações',
      'es': 'Mis viajes',
      'ja': '私の旅行',
      'pt': 'Minhas Viagens',
      'zh_Hans': '我的旅程',
      'zh_Hant': '我的旅行',
    },
    'ztv7x9i3': {
      'en': 'My Trips',
      'es': 'Mis viajes',
      'ja': '私の旅行',
      'pt': 'Minhas Viagens',
      'zh_Hans': '我的旅程',
      'zh_Hant': '我的旅行',
    },
  },
  // tripDetails
  {
    '7uozyw10': {
      'en': 'Trip Details',
      'es': 'Detalles del viaje',
      'ja': '旅行の詳細',
      'pt': 'Detalhes da viagem',
      'zh_Hans': '行程详情',
      'zh_Hant': '行程詳情',
    },
    '8vfkho8a': {
      'en': 'Dates of trip',
      'es': 'Fechas del viaje',
      'ja': '旅行の日程',
      'pt': 'Datas da viagem',
      'zh_Hans': '旅行日期',
      'zh_Hant': '旅行日期',
    },
    'niop5owj': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    'g3lyobnl': {
      'en': 'Destination',
      'es': 'Destino',
      'ja': '行き先',
      'pt': 'Destino',
      'zh_Hans': '目的地',
      'zh_Hant': '目的地',
    },
    'ihhb7ypu': {
      'en': 'Price Breakdown',
      'es': 'Desglose de precios',
      'ja': '価格の内訳',
      'pt': 'Repartição de preços',
      'zh_Hans': '价格明细',
      'zh_Hant': '價格細目',
    },
    'xbnrgozi': {
      'en': 'Base Price',
      'es': 'Precio base',
      'ja': '基本価格',
      'pt': 'Preço base',
      'zh_Hans': '基价',
      'zh_Hant': '基價',
    },
    'u45u8gcj': {
      'en': 'Taxes',
      'es': 'Impuestos',
      'ja': '税金',
      'pt': 'Impostos',
      'zh_Hans': '税费',
      'zh_Hant': '稅收',
    },
    'jadx0zpj': {
      'en': '\$24.20',
      'es': '\$24,20',
      'ja': '24.20ドル',
      'pt': '\$ 24,20',
      'zh_Hans': '24.20美元',
      'zh_Hant': '24.20 美元',
    },
    'mgi6y4wh': {
      'en': 'Cleaning Fee',
      'es': 'Tarifa de limpieza',
      'ja': '清掃料金',
      'pt': 'Taxa de limpeza',
      'zh_Hans': '清洁费',
      'zh_Hant': '清潔費',
    },
    'of4o3ptc': {
      'en': '\$40.00',
      'es': '\$40.00',
      'ja': '40.00ドル',
      'pt': '\$ 40,00',
      'zh_Hans': '40.00 美元',
      'zh_Hant': '40.00 美元',
    },
    'pph250s5': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'nxp76u8n': {
      'en': 'Your trip has been completed!',
      'es': '¡Tu viaje ha sido completado!',
      'ja': '旅行が完了しました!',
      'pt': 'Sua viagem foi concluída!',
      'zh_Hans': '您的旅程已完成！',
      'zh_Hant': '您的旅程已經完成！',
    },
    'at2rkkoh': {
      'en': 'Review Trip',
      'es': 'Reseña de viaje',
      'ja': '旅行のレビュー',
      'pt': 'Avaliar viagem',
      'zh_Hans': '回顾之旅',
      'zh_Hant': '回顧行程',
    },
    '66fynixt': {
      'en': 'Host Info',
      'es': 'Información del anfitrión',
      'ja': 'ホスト情報',
      'pt': 'Informações do anfitrião',
      'zh_Hans': '主人信息',
      'zh_Hant': '主機資訊',
    },
    'x7vkg9fs': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // propertyReview
  {
    'jsi1x6o3': {
      'en': 'Reviews',
      'es': 'Reseñas',
      'ja': 'レビュー',
      'pt': 'Avaliações',
      'zh_Hans': '评论',
      'zh_Hant': '評論',
    },
    '6kz56jwf': {
      'en': '# of Ratings',
      'es': '# de calificaciones',
      'ja': '評価数',
      'pt': '# de avaliações',
      'zh_Hans': '评分数',
      'zh_Hant': '分數',
    },
    'gyveynta': {
      'en': 'Avg. Rating',
      'es': 'Puntuación media',
      'ja': '平均評価',
      'pt': 'Classificação média',
      'zh_Hans': '平均评分',
      'zh_Hant': '平均。等級',
    },
    'yt004ng9': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // bookNow
  {
    'gdvzwz1x': {
      'en': 'Book Now',
      'es': 'Reservar ahora',
      'ja': '今すぐ予約',
      'pt': 'Reserve agora',
      'zh_Hans': '立即预订',
      'zh_Hant': '立即預訂',
    },
    'vox281q3': {
      'en': 'Choose Dates',
      'es': 'Seleccione Fechas',
      'ja': '日付を選択',
      'pt': 'Escolha as datas',
      'zh_Hans': '选择日期',
      'zh_Hant': '選擇日期',
    },
    'emf47njf': {
      'en': 'Number of Guests',
      'es': 'Número de invitados',
      'ja': 'ゲスト数',
      'pt': 'Número de convidados',
      'zh_Hans': '客人数量',
      'zh_Hant': '賓客人數',
    },
    '6i47fdrz': {
      'en': 'Choose an Option',
      'es': 'Elija una opción',
      'ja': 'オプションを選択',
      'pt': 'Escolha uma opção',
      'zh_Hans': '选择一个选项',
      'zh_Hant': '選擇一個選項',
    },
    'k9j4r7wn': {
      'en': 'Breakfast',
      'es': 'Desayuno',
      'ja': '朝食',
      'pt': 'Café da manhã',
      'zh_Hans': '早餐',
      'zh_Hant': '早餐',
    },
    'pomfl5zt': {
      'en': 'No Breakfast',
      'es': 'Sin desayuno',
      'ja': '朝食なし',
      'pt': 'Sem café da manhã',
      'zh_Hans': '不含早餐',
      'zh_Hant': '不含早餐',
    },
    'f1fe7s13': {
      'en': 'Hot Tub Access',
      'es': 'Acceso al jacuzzi',
      'ja': 'ホットタブへのアクセス',
      'pt': 'Acesso à banheira de hidromassagem',
      'zh_Hans': '热水浴缸',
      'zh_Hant': '使用熱水浴缸',
    },
    'zzic02za': {
      'en': 'No Access',
      'es': 'Sin acceso',
      'ja': 'アクセス不可',
      'pt': 'Sem acesso',
      'zh_Hans': '禁止访问',
      'zh_Hant': '無法訪問',
    },
    'w1yt4efz': {
      'en': 'Payment Information',
      'es': 'Información de pago',
      'ja': 'お支払い情報',
      'pt': 'Informações de pagamento',
      'zh_Hans': '付款信息',
      'zh_Hant': '付款資訊',
    },
    '525taf7s': {
      'en': 'Base Price',
      'es': 'Precio base',
      'ja': '基本価格',
      'pt': 'Preço base',
      'zh_Hans': '基价',
      'zh_Hant': '基價',
    },
    '15dzrmyu': {
      'en': '\$156.00',
      'es': '\$156.00',
      'ja': '156.00ドル',
      'pt': '\$ 156,00',
      'zh_Hans': '156.00 美元',
      'zh_Hant': '\$156.00',
    },
    'wqfxmh0o': {
      'en': 'Taxes',
      'es': 'Impuestos',
      'ja': '税金',
      'pt': 'Impostos',
      'zh_Hans': '税费',
      'zh_Hant': '稅收',
    },
    'dl9mjrer': {
      'en': '\$24.20',
      'es': '\$24,20',
      'ja': '24.20ドル',
      'pt': '\$ 24,20',
      'zh_Hans': '24.20美元',
      'zh_Hant': '24.20 美元',
    },
    'i7401er4': {
      'en': 'Cleaning Fee',
      'es': 'Tarifa de limpieza',
      'ja': '清掃料金',
      'pt': 'Taxa de limpeza',
      'zh_Hans': '清洁费',
      'zh_Hant': '清潔費',
    },
    '7dm8byl7': {
      'en': '\$40.00',
      'es': '\$40.00',
      'ja': '40.00ドル',
      'pt': '\$ 40,00',
      'zh_Hans': '40.00 美元',
      'zh_Hant': '40.00 美元',
    },
    'tq2cp1h5': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'zv9kebn7': {
      'en': '\$230.20',
      'es': '\$230,20',
      'ja': '230.20ドル',
      'pt': '\$ 230,20',
      'zh_Hans': '230.20 美元',
      'zh_Hant': '230.20 美元',
    },
    'eyvn9hcy': {
      'en': 'Book Now',
      'es': 'Reservar ahora',
      'ja': '今すぐ予約',
      'pt': 'Reserve agora',
      'zh_Hans': '立即预订',
      'zh_Hant': '立即預訂',
    },
    'y4keybpk': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // profilePage
  {
    'v2el0rh2': {
      'en': 'Switch to Dark Mode',
      'es': 'Cambiar al modo oscuro',
      'ja': 'ダークモードに切り替える',
      'pt': 'Mudar para o modo escuro',
      'zh_Hans': '切换到暗模式',
      'zh_Hant': '切換到深色模式',
    },
    'alzw08o2': {
      'en': 'Switch to Light Mode',
      'es': 'Cambiar al modo claro',
      'ja': 'ライトモードに切り替える',
      'pt': 'Mudar para o modo claro',
      'zh_Hans': '切换到灯光模式',
      'zh_Hant': '切換到燈光模式',
    },
    'gap2bgfi': {
      'en': 'Account Details',
      'es': 'Detalles de la cuenta',
      'ja': 'アカウントの詳細',
      'pt': 'Detalhes da conta',
      'zh_Hans': '帐户详细信息',
      'zh_Hant': '帳戶詳情',
    },
    '0z1zy5io': {
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'ja': 'プロフィールを編集',
      'pt': 'Editar Perfil',
      'zh_Hans': '編輯資料',
      'zh_Hant': '編輯個人資料',
    },
    '4kbtir5s': {
      'en': 'Payment Information',
      'es': 'Información de pago',
      'ja': 'お支払い情報',
      'pt': 'Informações de pagamento',
      'zh_Hans': '付款信息',
      'zh_Hant': '付款資訊',
    },
    '9fpw50qs': {
      'en': 'Change Password',
      'es': 'Cambiar la contraseña',
      'ja': 'パスワードを変更する',
      'pt': 'Alterar a senha',
      'zh_Hans': '更改密码',
      'zh_Hant': '更改密碼',
    },
    'z7cy46gl': {
      'en': 'My Properties',
      'es': 'Mis propiedades',
      'ja': '私のプロパティ',
      'pt': 'Minhas Propriedades',
      'zh_Hans': '我的房产',
      'zh_Hant': '我的房產',
    },
    'drg7mguv': {
      'en': 'My Bookings',
      'es': 'Mis reservas',
      'ja': '私の予約',
      'pt': 'Minhas Reservas',
      'zh_Hans': '我的预订',
      'zh_Hant': '我的預訂',
    },
    'imqcqtlo': {
      'en': 'Log Out',
      'es': 'Finalizar la sesión',
      'ja': 'ログアウト',
      'pt': 'Sair',
      'zh_Hans': '登出',
      'zh_Hant': '退出',
    },
    'agt31n9h': {
      'en': 'Add Property',
      'es': 'Agregar propiedad',
      'ja': 'プロパティを追加',
      'pt': 'Adicionar Propriedade',
      'zh_Hans': '添加属性',
      'zh_Hant': '新增屬性',
    },
    '30283g4v': {
      'en': 'Profile',
      'es': 'Perfil',
      'ja': 'プロフィール',
      'pt': 'Perfil',
      'zh_Hans': '轮廓',
      'zh_Hant': '輪廓',
    },
  },
  // paymentInfo
  {
    'pp28b715': {
      'en': 'Save Changes',
      'es': 'Guardar cambios',
      'ja': '変更を保存',
      'pt': 'Salvar alterações',
      'zh_Hans': '保存更改',
      'zh_Hant': '儲存變更',
    },
    'izy5n2uo': {
      'en': 'Payment Information',
      'es': 'Información de pago',
      'ja': 'お支払い情報',
      'pt': 'Informações de pagamento',
      'zh_Hans': '付款信息',
      'zh_Hant': '付款資訊',
    },
    'tu7di71z': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // editProfile
  {
    'wl1wrqj7': {
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'ja': 'プロフィールを編集',
      'pt': 'Editar Perfil',
      'zh_Hans': '編輯資料',
      'zh_Hant': '編輯個人資料',
    },
    'vmtxct7l': {
      'en': 'Change Photo',
      'es': 'Cambiar foto',
      'ja': '写真を変更',
      'pt': 'Alterar foto',
      'zh_Hans': '更改照片',
      'zh_Hant': '更改照片',
    },
    'qz4bjhsz': {
      'en': 'Full Name',
      'es': 'Nombre completo',
      'ja': 'フルネーム',
      'pt': 'Nome completo',
      'zh_Hans': '姓名',
      'zh_Hant': '姓名',
    },
    '9a6nvpeo': {
      'en': 'Your full name...',
      'es': 'Tu nombre completo...',
      'ja': 'あなたのフルネーム...',
      'pt': 'Seu nome completo...',
      'zh_Hans': '您的全名...',
      'zh_Hant': '你的全名...',
    },
    'jwwq0pzj': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'ja': '電子メールアドレス',
      'pt': 'Endereço de email',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    'qq3az6ke': {
      'en': 'Your email..',
      'es': 'Tu correo electrónico..',
      'ja': 'あなたのメールアドレス..',
      'pt': 'Seu e-mail..',
      'zh_Hans': '您的电子邮件..',
      'zh_Hant': '你的電子郵件..',
    },
    '55hnxor4': {
      'en': 'Bio',
      'es': 'Biografía',
      'ja': 'バイオ',
      'pt': 'Biografia',
      'zh_Hans': '个人简介',
      'zh_Hant': '簡介',
    },
    'h2ofz30r': {
      'en': 'A little about you...',
      'es': 'Un poco sobre ti...',
      'ja': 'あなたについて少し...',
      'pt': 'Um pouco sobre você...',
      'zh_Hans': '关于您一些信息...',
      'zh_Hant': '關於你的一點...',
    },
    '5h5zxmqc': {
      'en': 'Save Changes',
      'es': 'Guardar cambios',
      'ja': '変更を保存',
      'pt': 'Salvar alterações',
      'zh_Hans': '保存更改',
      'zh_Hant': '儲存變更',
    },
    'ezwpszd5': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // changePassword
  {
    '1wxwo2qp': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'ja': '電子メールアドレス',
      'pt': 'Endereço de email',
      'zh_Hans': '电子邮件',
      'zh_Hant': '電子郵件',
    },
    't2pg5he0': {
      'en': 'Your email..',
      'es': 'Tu correo electrónico..',
      'ja': 'あなたのメールアドレス..',
      'pt': 'Seu e-mail..',
      'zh_Hans': '您的电子邮件..',
      'zh_Hant': '你的電子郵件..',
    },
    'ljhhjimg': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account above.',
      'es':
          'Le enviaremos un correo electrónico con un enlace para restablecer su contraseña, ingrese el correo electrónico asociado a su cuenta arriba.',
      'ja':
          'パスワードをリセットするためのリンクが記載されたメールをお送りしますので、上記のアカウントに関連付けられているメールアドレスを入力してください。',
      'pt':
          'Enviaremos um e-mail com um link para redefinir sua senha. Insira o e-mail associado à sua conta acima.',
      'zh_Hans': '我们将向您发送一封电子邮件，其中包含重置密码的链接，请在上面输入与您的帐户关联的电子邮件。',
      'zh_Hant': '我們將向您發送一封電子郵件，其中包含重置密碼的鏈接，請在上面輸入與您的帳戶關聯的電子郵件。',
    },
    'eb2jrnmo': {
      'en': 'Send Reset Link',
      'es': 'Enviar enlace de restablecimiento',
      'ja': 'リセットリンクを送信',
      'pt': 'Enviar link de redefinição',
      'zh_Hans': '发送重置链接',
      'zh_Hant': '發送重置連結',
    },
    'yxwhoi9n': {
      'en': 'Change Password',
      'es': 'Cambiar la contraseña',
      'ja': 'パスワードを変更する',
      'pt': 'Alterar a senha',
      'zh_Hans': '更改密码',
      'zh_Hant': '更改密碼',
    },
    't5tdhver': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // createProperty_1
  {
    'ec6w5msp': {
      'en': 'PROPERTY NAME',
      'es': 'NOMBRE DE LA PROPIEDAD',
      'ja': '物件名',
      'pt': 'NOME DO IMÓVEL',
      'zh_Hans': '物业名称',
      'zh_Hant': '物業名稱',
    },
    'qa7yegsx': {
      'en': 'Something Catchy...',
      'es': 'Algo pegadizo...',
      'ja': '何かキャッチーなもの...',
      'pt': 'Algo cativante...',
      'zh_Hans': '一些引人注目的东西……',
      'zh_Hant': '有什麼吸引人的...',
    },
    'x2e2qcnx': {
      'en': 'PROPERTY ADDRESS',
      'es': 'DIRECCIÓN DE LA PROPIEDAD',
      'ja': '物件住所',
      'pt': 'ENDEREÇO DO IMÓVEL',
      'zh_Hans': '物业地址',
      'zh_Hant': '物業地址',
    },
    'fpmbgcfs': {
      'en': '123 Disney way here…',
      'es': '123 Disney way aquí…',
      'ja': '123 Disney wayはここです…',
      'pt': '123 Disney way aqui…',
      'zh_Hans': '123 迪士尼路…',
      'zh_Hant': '123 迪士尼路在這裡…',
    },
    'rhy1csz2': {
      'en': 'NEIGHBORHOOD',
      'es': 'VECINDARIO',
      'ja': '近所',
      'pt': 'VIZINHANÇA',
      'zh_Hans': '邻里',
      'zh_Hant': '鄰裡',
    },
    '8oikrzu3': {
      'en': 'Neighborhood or city…',
      'es': 'Barrio o ciudad…',
      'ja': '近所や街…',
      'pt': 'Bairro ou cidade…',
      'zh_Hans': '社区或城市…',
      'zh_Hant': '社區或城市...',
    },
    '61ot6t0g': {
      'en': 'DESCRIPTION',
      'es': 'DESCRIPCIÓN',
      'ja': '説明',
      'pt': 'DESCRIÇÃO',
      'zh_Hans': '描述',
      'zh_Hant': '描述',
    },
    '0yirrp0r': {
      'en': 'Neighborhood or city…',
      'es': 'Barrio o ciudad…',
      'ja': '近所や街…',
      'pt': 'Bairro ou cidade…',
      'zh_Hans': '社区或城市…',
      'zh_Hant': '社區或城市...',
    },
    'iy5xhksa': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    '6cl1e8r7': {
      'en': '1/3',
      'es': '1/3',
      'ja': '1/3',
      'pt': '1/3',
      'zh_Hans': '1/3',
      'zh_Hant': '1/3',
    },
    '4au9bfrp': {
      'en': 'NEXT',
      'es': 'PRÓXIMO',
      'ja': '次',
      'pt': 'PRÓXIMO',
      'zh_Hans': '下一个',
      'zh_Hant': '下一個',
    },
    'e0vd159s': {
      'en': 'Create Property',
      'es': 'Crear propiedad',
      'ja': 'プロパティの作成',
      'pt': 'Criar Propriedade',
      'zh_Hans': '创建属性',
      'zh_Hant': '創建財產',
    },
    'uf0zkloi': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // HomePage_ALT
  {
    'f3m36y00': {
      'en': 'Welcome!',
      'es': '¡Bienvenido!',
      'ja': 'いらっしゃいませ！',
      'pt': 'Bem-vindo!',
      'zh_Hans': '欢迎！',
      'zh_Hant': '歡迎！',
    },
    'n9eizxvz': {
      'en': 'Find your Dream Space',
      'es': 'Encuentra el espacio de tus sueños',
      'ja': '夢の空間を見つけよう',
      'pt': 'Encontre o espaço dos seus sonhos',
      'zh_Hans': '找到你的梦想空间',
      'zh_Hant': '尋找你的夢想空間',
    },
    'dzyixwul': {
      'en': 'Address, city, state...',
      'es': 'Dirección, ciudad, estado...',
      'ja': '住所、市、州...',
      'pt': 'Endereço, cidade, estado...',
      'zh_Hans': '地址、城市、州...',
      'zh_Hant': '地址、城市、州...',
    },
    'q2ru2s0r': {
      'en': 'Search',
      'es': 'Buscar',
      'ja': '検索',
      'pt': 'Procurar',
      'zh_Hans': '搜索',
      'zh_Hant': '搜尋',
    },
    '7sjvdjz3': {
      'en': '4/5 reviews',
      'es': '4/5 opiniones',
      'ja': '4/5 レビュー',
      'pt': '4/5 avaliações',
      'zh_Hans': '4/5 条评论',
      'zh_Hant': '4/5 評論',
    },
    'xmpkvsbp': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // createProperty_2
  {
    'pdbfx8hf': {
      'en': 'Create Property',
      'es': 'Crear propiedad',
      'ja': 'プロパティの作成',
      'pt': 'Criar Propriedade',
      'zh_Hans': '创建属性',
      'zh_Hant': '創建財產',
    },
    'y0smh4kt': {
      'en': 'CHOOSE YOUR AMENITIES',
      'es': 'ELIGE TUS COMODIDADES',
      'ja': 'アメニティをお選びください',
      'pt': 'ESCOLHA SUAS COMODIDADES',
      'zh_Hans': '选择您的便利设施',
      'zh_Hant': '選擇您的設施',
    },
    'fcjq479t': {
      'en': 'Pool',
      'es': 'Piscina',
      'ja': 'プール',
      'pt': 'Piscina',
      'zh_Hans': '水池',
      'zh_Hant': '水池',
    },
    'yh0qdmj7': {
      'en': 'EV Car Charging',
      'es': 'Carga de vehículos eléctricos',
      'ja': 'EV車の充電',
      'pt': 'Carregamento de carros elétricos',
      'zh_Hans': '电动汽车充电',
      'zh_Hant': '電動車充電',
    },
    '8yw6l5zu': {
      'en': 'Extra Outlets',
      'es': 'Tomas de corriente adicionales',
      'ja': '追加コンセント',
      'pt': 'Saídas extras',
      'zh_Hans': '额外出口',
      'zh_Hant': '額外插座',
    },
    'i27q73rs': {
      'en': 'Air Conditioning (AC)',
      'es': 'Aire acondicionado (AC)',
      'ja': 'エアコン（AC）',
      'pt': 'Ar condicionado (AC)',
      'zh_Hans': '空调',
      'zh_Hant': '空調（交流）',
    },
    'eamb2ctg': {
      'en': 'Heating',
      'es': 'Calefacción',
      'ja': '加熱',
      'pt': 'Aquecimento',
      'zh_Hans': '加热',
      'zh_Hant': '加熱',
    },
    'rodptns4': {
      'en': 'Washer',
      'es': 'Arandela',
      'ja': 'ワッシャー',
      'pt': 'Máquina de lavar',
      'zh_Hans': '垫圈',
      'zh_Hant': '墊圈',
    },
    'tvxdy0pp': {
      'en': 'Dryer',
      'es': 'Secadora',
      'ja': 'ドライヤー',
      'pt': 'Secador',
      'zh_Hans': '烘干机',
      'zh_Hant': '烘乾機',
    },
    'bzjn5plq': {
      'en': 'Pet Friendly',
      'es': 'Se aceptan mascotas',
      'ja': 'ペット可',
      'pt': 'Aceita animais de estimação',
      'zh_Hans': '可携带宠物',
      'zh_Hant': '允許攜帶寵物',
    },
    'hl8565ar': {
      'en': 'Workout Facility',
      'es': 'Instalaciones para hacer ejercicio',
      'ja': 'トレーニング施設',
      'pt': 'Instalações de treino',
      'zh_Hans': '健身设施',
      'zh_Hant': '健身設施',
    },
    'pf4x3nsg': {
      'en': 'Hip',
      'es': 'Cadera',
      'ja': 'ヒップ',
      'pt': 'Quadril',
      'zh_Hans': '时髦的',
      'zh_Hant': '時髦的',
    },
    '2g1pd0zt': {
      'en': 'Night Life',
      'es': 'Vida nocturna',
      'ja': 'ナイトライフ',
      'pt': 'Vida noturna',
      'zh_Hans': '夜生活',
      'zh_Hant': '夜生活',
    },
    '941fdqii': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    'jvqfwjfu': {
      'en': '2/3',
      'es': '2/3',
      'ja': '2/3',
      'pt': '2/3',
      'zh_Hans': '2/3',
      'zh_Hant': '2/3',
    },
    '04z704wi': {
      'en': 'NEXT',
      'es': 'PRÓXIMO',
      'ja': '次',
      'pt': 'PRÓXIMO',
      'zh_Hans': '下一个',
      'zh_Hant': '下一個',
    },
    'hxpg7eia': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // createProperty_3
  {
    'g8qpujkp': {
      'en': 'Create Property',
      'es': 'Crear propiedad',
      'ja': 'プロパティの作成',
      'pt': 'Criar Propriedade',
      'zh_Hans': '创建属性',
      'zh_Hant': '創建財產',
    },
    'vvvh7q2y': {
      'en': 'PRICE PER NIGHT',
      'es': 'PRECIO POR NOCHE',
      'ja': '1泊あたりの料金',
      'pt': 'PREÇO POR NOITE',
      'zh_Hans': '每晚价格',
      'zh_Hant': '每晚價格',
    },
    '2n5962sn': {
      'en': '\$ Price',
      'es': '\$ Precio',
      'ja': '\$ 価格',
      'pt': '\$ Preço',
      'zh_Hans': '\$ 价格',
      'zh_Hant': '\$ 價格',
    },
    'eze623h2': {
      'en': 'MINIMUM NIGHT STAY',
      'es': 'ESTANCIA MÍNIMA POR NOCHE',
      'ja': '最低宿泊日数',
      'pt': 'PERMANÊNCIA MÍNIMA DE NOITE',
      'zh_Hans': '最少住宿晚数',
      'zh_Hant': '最短住宿天數',
    },
    '3u0bp805': {
      'en': 'TAX RATE',
      'es': 'TASA IMPOSITIVA',
      'ja': '税率',
      'pt': 'TAXA DE IMPOSTO',
      'zh_Hans': '税率',
      'zh_Hant': '稅率',
    },
    'ilflwx93': {
      'en': '% Rate',
      'es': '% Tasa',
      'ja': '％ レート',
      'pt': '% Avaliar',
      'zh_Hans': '％ 速度',
      'zh_Hant': '％ 速度',
    },
    'tfk6so2d': {
      'en': 'CLEANING FEE',
      'es': 'TARIFA DE LIMPIEZA',
      'ja': '清掃料金',
      'pt': 'TAXA DE LIMPEZA',
      'zh_Hans': '清洁费',
      'zh_Hant': '清潔費',
    },
    'ylljd6pe': {
      'en': '\$ Price',
      'es': '\$ Precio',
      'ja': '\$ 価格',
      'pt': '\$ Preço',
      'zh_Hans': '\$ 价格',
      'zh_Hant': '\$ 價格',
    },
    '9ez8haol': {
      'en': 'Additional Notes',
      'es': 'Notas adicionales',
      'ja': '追加メモ',
      'pt': 'Notas adicionais',
      'zh_Hans': '其他说明',
      'zh_Hant': '附加說明',
    },
    'b792jo3u': {
      'en': 'Additional notes...',
      'es': 'Notas adicionales...',
      'ja': '追加メモ...',
      'pt': 'Notas adicionais...',
      'zh_Hans': '补充说明...',
      'zh_Hant': '附加說明...',
    },
    'a9m7xo9a': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    '9xs2z1z3': {
      'en': '3/3',
      'es': '3/3',
      'ja': '3/3',
      'pt': '3/3',
      'zh_Hans': '3/3',
      'zh_Hant': '3/3',
    },
    'v9kfob53': {
      'en': 'PUBLISH',
      'es': 'PUBLICAR',
      'ja': '公開',
      'pt': 'PUBLICAR',
      'zh_Hans': '发布',
      'zh_Hant': '發布',
    },
    'pax7m0z7': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // myProperties
  {
    'vyb1jce1': {
      'en': 'Published',
      'es': 'Publicado',
      'ja': '公開済み',
      'pt': 'Publicado',
      'zh_Hans': '发布',
      'zh_Hant': '已發表',
    },
    'cy9lnkzk': {
      'en': 'Price Per Night',
      'es': 'Precio por noche',
      'ja': '1泊あたりの料金',
      'pt': 'Preço por noite',
      'zh_Hans': '每晚价格',
      'zh_Hant': '每晚價格',
    },
    '2z2jgfd6': {
      'en': 'Drafts',
      'es': 'Damas',
      'ja': 'ドラフト',
      'pt': 'Rascunhos',
      'zh_Hans': '草稿',
      'zh_Hant': '草稿',
    },
    'yp84hdow': {
      'en': 'Price Per Night',
      'es': 'Precio por noche',
      'ja': '1泊あたりの料金',
      'pt': 'Preço por noite',
      'zh_Hans': '每晚价格',
      'zh_Hant': '每晚價格',
    },
    'n1noxy29': {
      'en': 'My Properties',
      'es': 'Mis propiedades',
      'ja': '私のプロパティ',
      'pt': 'Minhas Propriedades',
      'zh_Hans': '我的房产',
      'zh_Hant': '我的房產',
    },
    'fv9bbuwi': {
      'en': 'My Trips',
      'es': 'Mis viajes',
      'ja': '私の旅行',
      'pt': 'Minhas Viagens',
      'zh_Hans': '我的旅程',
      'zh_Hant': '我的旅行',
    },
  },
  // propertyDetails_Owner
  {
    'dw3ipvw8': {
      'en': 'Reviews',
      'es': 'Reseñas',
      'ja': 'レビュー',
      'pt': 'Avaliações',
      'zh_Hans': '评论',
      'zh_Hant': '評論',
    },
    'g2jiwyel': {
      'en': 'DESCRIPTION',
      'es': 'DESCRIPCIÓN',
      'ja': '説明',
      'pt': 'DESCRIÇÃO',
      'zh_Hans': '描述',
      'zh_Hant': '描述',
    },
    'd9n6ms4b': {
      'en': 'Amenities',
      'es': 'Comodidades',
      'ja': 'アメニティ',
      'pt': 'Comodidades',
      'zh_Hans': '便利设施',
      'zh_Hant': '便利設施',
    },
    'jaxffzuq': {
      'en': 'What people are saying',
      'es': 'Lo que la gente está diciendo',
      'ja': '人々が言っていること',
      'pt': 'O que as pessoas estão dizendo',
      'zh_Hans': '人们在说什么',
      'zh_Hant': '人們在說什麼',
    },
    '3z10w1jg': {
      'en': 'Josh Richardson',
      'es': 'Josh Richardson',
      'ja': 'ジョシュ・リチャードソン',
      'pt': 'Josh Richardson',
      'zh_Hans': '乔希·理查德森',
      'zh_Hant': '喬許·理查森',
    },
    'uj6fy1xm': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'es':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'ja':
          'ロレム・イプサム・ドルー・シット・アメット、コンセクト・アディピシング・エリート、セド・ド・エイウスモッド・テンポラ・インシディダント・ユー・レイバーとドローレ・マグナ・アリクア。最低限のお金は必要です...',
      'pt':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidente ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'zh_Hans':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可爱的小兔子图片大全 可爱的小兔子设计素材 可爱的兔子模板下载 可爱...',
      'zh_Hant':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可愛的小兔子圖片大全 可愛的小兔子設計素材 可愛的兔子模板下載 可愛...',
    },
    'ebeuzb2x': {
      'en': 'Josh Richardson',
      'es': 'Josh Richardson',
      'ja': 'ジョシュ・リチャードソン',
      'pt': 'Josh Richardson',
      'zh_Hans': '乔希·理查德森',
      'zh_Hant': '喬許·理查森',
    },
    'em2317b9': {
      'en':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'es':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'ja':
          'ロレム・イプサム・ドルー・シット・アメット、コンセクト・アディピシング・エリート、セド・ド・エイウスモッド・テンポラ・インシディダント・ユー・レイバーとドローレ・マグナ・アリクア。最低限のお金は必要です...',
      'pt':
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidente ut labore et dolore magna aliqua. Ut enim ad minim veniam...',
      'zh_Hans':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可爱的小兔子图片大全 可爱的小兔子设计素材 可爱的兔子模板下载 可爱...',
      'zh_Hant':
          'Lorem ipsum dolor sat amet，consectetur adipiscing elit，sed do eiusmod tempor incididunt ut laboure et dolore magna aliqua。可愛的小兔子向量素材下載 非凡圖庫...',
    },
    'qmw085j5': {
      'en': '\$156',
      'es': '\$156',
      'ja': '156ドル',
      'pt': '\$ 156',
      'zh_Hans': '\$156',
      'zh_Hant': '156 美元',
    },
    '9xye8cft': {
      'en': '+ taxes/fees',
      'es': '+ impuestos/tarifas',
      'ja': '+ 税金/手数料',
      'pt': '+ impostos/taxas',
      'zh_Hans': '+ 税费',
      'zh_Hant': '+ 稅金/費用',
    },
    'xtcjp6c0': {
      'en': 'per night',
      'es': 'por noche',
      'ja': '1泊あたり',
      'pt': 'por noite',
      'zh_Hans': '每晚',
      'zh_Hant': '每晚',
    },
    'bar345x7': {
      'en': 'Edit Property',
      'es': 'Editar propiedad',
      'ja': 'プロパティの編集',
      'pt': 'Editar Propriedade',
      'zh_Hans': '編輯財產',
      'zh_Hant': '編輯屬性',
    },
    'o2h17dzz': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // myBookings
  {
    'p6qb5mcv': {
      'en': 'Upcoming ',
      'es': 'Próximamente',
      'ja': '今後の予定',
      'pt': 'Por vir',
      'zh_Hans': '即将推出',
      'zh_Hant': '即將推出',
    },
    'tif8yewd': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    '19v1m7pp': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'rz7ienpu': {
      'en': 'Completed',
      'es': 'Terminado',
      'ja': '完了',
      'pt': 'Concluído',
      'zh_Hans': '完全的',
      'zh_Hant': '完全的',
    },
    'r0jzgvid': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    'wwq7kan5': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'ja5rvi1k': {
      'en': 'My Bookings',
      'es': 'Mis reservas',
      'ja': '私の予約',
      'pt': 'Minhas Reservas',
      'zh_Hans': '我的预订',
      'zh_Hant': '我的預訂',
    },
    'ra9pl4gw': {
      'en': 'My Trips',
      'es': 'Mis viajes',
      'ja': '私の旅行',
      'pt': 'Minhas Viagens',
      'zh_Hans': '我的旅程',
      'zh_Hant': '我的旅行',
    },
  },
  // tripDetailsHOST
  {
    '00utioom': {
      'en': 'Trip Details',
      'es': 'Detalles del viaje',
      'ja': '旅行の詳細',
      'pt': 'Detalhes da viagem',
      'zh_Hans': '行程详情',
      'zh_Hant': '行程詳情',
    },
    '77utvge7': {
      'en': 'Dates of trip',
      'es': 'Fechas del viaje',
      'ja': '旅行の日程',
      'pt': 'Datas da viagem',
      'zh_Hans': '旅行日期',
      'zh_Hant': '旅行日期',
    },
    'h1xcfwef': {
      'en': ' - ',
      'es': '-',
      'ja': '-',
      'pt': '-',
      'zh_Hans': '-',
      'zh_Hant': '-',
    },
    'm6fl3576': {
      'en': 'Destination',
      'es': 'Destino',
      'ja': '行き先',
      'pt': 'Destino',
      'zh_Hans': '目的地',
      'zh_Hant': '目的地',
    },
    'sp8msdit': {
      'en': 'Price Breakdown',
      'es': 'Desglose de precios',
      'ja': '価格の内訳',
      'pt': 'Repartição de preços',
      'zh_Hans': '价格明细',
      'zh_Hant': '價格細目',
    },
    'sffvy1t2': {
      'en': 'Base Price',
      'es': 'Precio base',
      'ja': '基本価格',
      'pt': 'Preço base',
      'zh_Hans': '基价',
      'zh_Hant': '基價',
    },
    'kkzu0vat': {
      'en': 'Taxes',
      'es': 'Impuestos',
      'ja': '税金',
      'pt': 'Impostos',
      'zh_Hans': '税费',
      'zh_Hant': '稅收',
    },
    '9rr5tjhq': {
      'en': '\$24.20',
      'es': '\$24,20',
      'ja': '24.20ドル',
      'pt': '\$ 24,20',
      'zh_Hans': '24.20美元',
      'zh_Hant': '24.20 美元',
    },
    '2ulucdke': {
      'en': 'Cleaning Fee',
      'es': 'Tarifa de limpieza',
      'ja': '清掃料金',
      'pt': 'Taxa de limpeza',
      'zh_Hans': '清洁费',
      'zh_Hant': '清潔費',
    },
    'c96rmndc': {
      'en': '\$40.00',
      'es': '\$40.00',
      'ja': '40.00ドル',
      'pt': '\$ 40,00',
      'zh_Hans': '40.00 美元',
      'zh_Hant': '40.00 美元',
    },
    '1qntl58m': {
      'en': 'Total',
      'es': 'Total',
      'ja': '合計',
      'pt': 'Total',
      'zh_Hans': '全部的',
      'zh_Hant': '全部的',
    },
    'efj2o489': {
      'en': 'Mark this trip as complete below.',
      'es': 'Marca este viaje como completo a continuación.',
      'ja': 'この旅行を以下で完了としてマークします。',
      'pt': 'Marque esta viagem como concluída abaixo.',
      'zh_Hans': '在下方将此行程标记为已完成。',
      'zh_Hant': '下面將這次旅行標記為完成。',
    },
    'zh9h2mgp': {
      'en': 'Mark as Complete',
      'es': 'Marcar como completo',
      'ja': '完了としてマーク',
      'pt': 'Marcar como concluído',
      'zh_Hans': '标记为完成',
      'zh_Hant': '標記為完成',
    },
    'w5bae1ja': {
      'en': 'Guest Info',
      'es': 'Información para invitados',
      'ja': 'ゲスト情報',
      'pt': 'Informações para hóspedes',
      'zh_Hans': '宾客信息',
      'zh_Hant': '賓客資訊',
    },
    'ksm3zayg': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // editProperty_1
  {
    'fec8kerj': {
      'en': 'Edit Property',
      'es': 'Editar propiedad',
      'ja': 'プロパティの編集',
      'pt': 'Editar Propriedade',
      'zh_Hans': '編輯財產',
      'zh_Hant': '編輯屬性',
    },
    'qje2h8iz': {
      'en': 'PROPERTY NAME',
      'es': 'NOMBRE DE LA PROPIEDAD',
      'ja': '物件名',
      'pt': 'NOME DO IMÓVEL',
      'zh_Hans': '物业名称',
      'zh_Hant': '物業名稱',
    },
    '11djavwz': {
      'en': 'Something Catchy...',
      'es': 'Algo pegadizo...',
      'ja': '何かキャッチーなもの...',
      'pt': 'Algo cativante...',
      'zh_Hans': '一些引人注目的东西……',
      'zh_Hant': '有什麼吸引人的...',
    },
    'wllvzsji': {
      'en': 'PROPERTY ADDRESS',
      'es': 'DIRECCIÓN DE LA PROPIEDAD',
      'ja': '物件住所',
      'pt': 'ENDEREÇO DO IMÓVEL',
      'zh_Hans': '物业地址',
      'zh_Hant': '物業地址',
    },
    'z69ztlfe': {
      'en': '123 Disney way here…',
      'es': '123 Disney way aquí…',
      'ja': '123 Disney wayはここです…',
      'pt': '123 Disney way aqui…',
      'zh_Hans': '123 迪士尼路…',
      'zh_Hant': '123 迪士尼路在這裡…',
    },
    'u35wue56': {
      'en': 'NEIGHBORHOOD',
      'es': 'VECINDARIO',
      'ja': '近所',
      'pt': 'VIZINHANÇA',
      'zh_Hans': '邻里',
      'zh_Hant': '鄰裡',
    },
    '66x89lg8': {
      'en': 'Neighborhood or city…',
      'es': 'Barrio o ciudad…',
      'ja': '近所や街…',
      'pt': 'Bairro ou cidade…',
      'zh_Hans': '社区或城市…',
      'zh_Hant': '社區或城市...',
    },
    'czy3xvqn': {
      'en': 'DESCRIPTION',
      'es': 'DESCRIPCIÓN',
      'ja': '説明',
      'pt': 'DESCRIÇÃO',
      'zh_Hans': '描述',
      'zh_Hant': '描述',
    },
    'xdf8cjay': {
      'en': 'Neighborhood or city…',
      'es': 'Barrio o ciudad…',
      'ja': '近所や街…',
      'pt': 'Bairro ou cidade…',
      'zh_Hans': '社区或城市…',
      'zh_Hant': '社區或城市...',
    },
    'pa2ntbph': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    'zvmzkuz5': {
      'en': '1/3',
      'es': '1/3',
      'ja': '1/3',
      'pt': '1/3',
      'zh_Hans': '1/3',
      'zh_Hant': '1/3',
    },
    'j7tx7w8y': {
      'en': 'NEXT',
      'es': 'PRÓXIMO',
      'ja': '次',
      'pt': 'PRÓXIMO',
      'zh_Hans': '下一个',
      'zh_Hant': '下一個',
    },
    'o0r6lrkp': {
      'en': 'We need to know the name of the place...',
      'es': 'Necesitamos saber el nombre del lugar...',
      'ja': 'その場所の名前を知る必要があります...',
      'pt': 'Precisamos saber o nome do lugar...',
      'zh_Hans': '我们需要知道这个地方的名字...',
      'zh_Hant': '我們需要知道這個地方的名字...',
    },
    '20p6ecbe': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // editProperty_2
  {
    '7ko67b7p': {
      'en': 'Edit Property',
      'es': 'Editar propiedad',
      'ja': 'プロパティの編集',
      'pt': 'Editar Propriedade',
      'zh_Hans': '編輯財產',
      'zh_Hant': '編輯屬性',
    },
    'nuqbo8xz': {
      'en': 'CHOOSE YOUR AMENITIES',
      'es': 'ELIGE TUS COMODIDADES',
      'ja': 'アメニティをお選びください',
      'pt': 'ESCOLHA SUAS COMODIDADES',
      'zh_Hans': '选择您的便利设施',
      'zh_Hant': '選擇您的設施',
    },
    'il5fpnnb': {
      'en': 'Pool',
      'es': 'Piscina',
      'ja': 'プール',
      'pt': 'Piscina',
      'zh_Hans': '水池',
      'zh_Hant': '水池',
    },
    'hensjka0': {
      'en': 'EV Car Charging',
      'es': 'Carga de vehículos eléctricos',
      'ja': 'EV車の充電',
      'pt': 'Carregamento de carros elétricos',
      'zh_Hans': '电动汽车充电',
      'zh_Hant': '電動車充電',
    },
    'vrt8edc5': {
      'en': 'Extra Outlets',
      'es': 'Tomas de corriente adicionales',
      'ja': '追加コンセント',
      'pt': 'Saídas extras',
      'zh_Hans': '额外出口',
      'zh_Hant': '額外插座',
    },
    '8firgxvw': {
      'en': 'Air Conditioning (AC)',
      'es': 'Aire acondicionado (AC)',
      'ja': 'エアコン（AC）',
      'pt': 'Ar condicionado (AC)',
      'zh_Hans': '空调',
      'zh_Hant': '空調（交流）',
    },
    'zt9vkk3o': {
      'en': 'Heating',
      'es': 'Calefacción',
      'ja': '加熱',
      'pt': 'Aquecimento',
      'zh_Hans': '加热',
      'zh_Hant': '加熱',
    },
    '46c7hsgh': {
      'en': 'Washer',
      'es': 'Arandela',
      'ja': 'ワッシャー',
      'pt': 'Máquina de lavar',
      'zh_Hans': '垫圈',
      'zh_Hant': '墊圈',
    },
    'nuukc3x8': {
      'en': 'Dryer',
      'es': 'Secadora',
      'ja': 'ドライヤー',
      'pt': 'Secador',
      'zh_Hans': '烘干机',
      'zh_Hant': '烘乾機',
    },
    '4n1ljusf': {
      'en': 'Pet Friendly',
      'es': 'Se aceptan mascotas',
      'ja': 'ペット可',
      'pt': 'Aceita animais de estimação',
      'zh_Hans': '可携带宠物',
      'zh_Hant': '允許攜帶寵物',
    },
    'v58mnstq': {
      'en': 'Workout Facility',
      'es': 'Instalaciones para hacer ejercicio',
      'ja': 'トレーニング施設',
      'pt': 'Instalações de treino',
      'zh_Hans': '健身设施',
      'zh_Hant': '健身設施',
    },
    'ufjjntiw': {
      'en': 'Hip',
      'es': 'Cadera',
      'ja': 'ヒップ',
      'pt': 'Quadril',
      'zh_Hans': '时髦的',
      'zh_Hant': '時髦的',
    },
    'l0182brh': {
      'en': 'Night Life',
      'es': 'Vida nocturna',
      'ja': 'ナイトライフ',
      'pt': 'Vida noturna',
      'zh_Hans': '夜生活',
      'zh_Hant': '夜生活',
    },
    '5k2lcl9e': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    'yrnvppyx': {
      'en': '2/3',
      'es': '2/3',
      'ja': '2/3',
      'pt': '2/3',
      'zh_Hans': '2/3',
      'zh_Hant': '2/3',
    },
    'sh2ruo9b': {
      'en': 'NEXT',
      'es': 'PRÓXIMO',
      'ja': '次',
      'pt': 'PRÓXIMO',
      'zh_Hans': '下一个',
      'zh_Hant': '下一個',
    },
    'ebgeto75': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // editProperty_3
  {
    '0gikjxn7': {
      'en': 'Edit Property',
      'es': 'Editar propiedad',
      'ja': 'プロパティの編集',
      'pt': 'Editar Propriedade',
      'zh_Hans': '編輯財產',
      'zh_Hant': '編輯屬性',
    },
    'd9lxul2x': {
      'en': 'PRICE PER NIGHT',
      'es': 'PRECIO POR NOCHE',
      'ja': '1泊あたりの料金',
      'pt': 'PREÇO POR NOITE',
      'zh_Hans': '每晚价格',
      'zh_Hant': '每晚價格',
    },
    'itkolirp': {
      'en': '\$ Price',
      'es': '\$ Precio',
      'ja': '\$ 価格',
      'pt': '\$ Preço',
      'zh_Hans': '\$ 价格',
      'zh_Hant': '\$ 價格',
    },
    'digj003b': {
      'en': 'MINIMUM NIGHT STAY',
      'es': 'ESTANCIA MÍNIMA POR NOCHE',
      'ja': '最低宿泊日数',
      'pt': 'PERMANÊNCIA MÍNIMA DE NOITE',
      'zh_Hans': '最少住宿晚数',
      'zh_Hant': '最短住宿天數',
    },
    'jnsl8faa': {
      'en': 'TAX RATE',
      'es': 'TASA IMPOSITIVA',
      'ja': '税率',
      'pt': 'TAXA DE IMPOSTO',
      'zh_Hans': '税率',
      'zh_Hant': '稅率',
    },
    '5etk5fdz': {
      'en': '% Rate',
      'es': '% Tasa',
      'ja': '％ レート',
      'pt': '% Avaliar',
      'zh_Hans': '％ 速度',
      'zh_Hant': '％ 速度',
    },
    'p6yf6nzz': {
      'en': 'CLEANING FEE',
      'es': 'TARIFA DE LIMPIEZA',
      'ja': '清掃料金',
      'pt': 'TAXA DE LIMPEZA',
      'zh_Hans': '清洁费',
      'zh_Hant': '清潔費',
    },
    'zvj3xwb1': {
      'en': '\$ Price',
      'es': '\$ Precio',
      'ja': '\$ 価格',
      'pt': '\$ Preço',
      'zh_Hans': '\$ 价格',
      'zh_Hant': '\$ 價格',
    },
    '0km689en': {
      'en': 'Additional Notes',
      'es': 'Notas adicionales',
      'ja': '追加メモ',
      'pt': 'Notas adicionais',
      'zh_Hans': '其他说明',
      'zh_Hant': '附加說明',
    },
    '77mqc8xc': {
      'en': 'Additional notes...',
      'es': 'Notas adicionales...',
      'ja': '追加メモ...',
      'pt': 'Notas adicionais...',
      'zh_Hans': '补充说明...',
      'zh_Hant': '附加說明...',
    },
    'pqhjsqqi': {
      'en': 'Listing is Live',
      'es': 'El listado está activo',
      'ja': 'リストは公開中です',
      'pt': 'A listagem está ativa',
      'zh_Hans': '房源已上线',
      'zh_Hant': '清單已上線',
    },
    '3aygstkd': {
      'en': 'Turn this on for guests to start booking your listing.',
      'es':
          'Active esta opción para que los invitados comiencen a reservar su anuncio.',
      'ja': 'これをオンにすると、ゲストがリスティングの予約を開始できるようになります。',
      'pt':
          'Ative esta opção para que os hóspedes possam começar a reservar seu anúncio.',
      'zh_Hans': '启用此功能后，客人就可以开始预订您的房源。',
      'zh_Hant': '開啟此選項，房客即可開始預訂您的房源。',
    },
    'c8suv3sh': {
      'en': 'STEP',
      'es': 'PASO',
      'ja': 'ステップ',
      'pt': 'ETAPA',
      'zh_Hans': '步',
      'zh_Hant': '步',
    },
    'd7gzhv5m': {
      'en': '3/3',
      'es': '3/3',
      'ja': '3/3',
      'pt': '3/3',
      'zh_Hans': '3/3',
      'zh_Hant': '3/3',
    },
    'bry9m7vz': {
      'en': 'Save Changes',
      'es': 'Guardar cambios',
      'ja': '変更を保存',
      'pt': 'Salvar alterações',
      'zh_Hans': '保存更改',
      'zh_Hant': '儲存變更',
    },
    'l3bcix2i': {
      'en': 'Home',
      'es': 'Hogar',
      'ja': '家',
      'pt': 'Lar',
      'zh_Hans': '家',
      'zh_Hant': '家',
    },
  },
  // bottomSheet
  {
    'tdiesok1': {
      'en': 'Session Booked!',
      'es': '¡Sesión reservada!',
      'ja': 'セッションが予約されました!',
      'pt': 'Sessão reservada!',
      'zh_Hans': '会议已预订！',
      'zh_Hant': '會議已預訂！',
    },
    'acsyxxnr': {
      'en': 'You have successfully booked a session on:',
      'es': 'Has reservado con éxito una sesión en:',
      'ja': '以下のセッションの予約が完了しました:',
      'pt': 'Você reservou com sucesso uma sessão em:',
      'zh_Hans': '您已成功预订了以下课程：',
      'zh_Hant': '您已成功預訂以下課程：',
    },
    'mi03qqjs': {
      'en': 'Mon, Dec 11 - 2021',
      'es': 'Lunes 11 de diciembre de 2021',
      'ja': '2021年12月11日（月）',
      'pt': 'Seg, 11 Dez - 2021',
      'zh_Hans': '2021 年 12 月 11 日（周一）',
      'zh_Hant': '2021 年 12 月 11 日星期一',
    },
  },
  // total
  {
    'oj7rcpv7': {
      'en': 'Order Total',
      'es': 'Total del pedido',
      'ja': '注文合計',
      'pt': 'Total do pedido',
      'zh_Hans': '订单总额',
      'zh_Hant': '訂單總計',
    },
    'l109nxqx': {
      'en':
          'Your order total is a summary of all items in your order minus any fees and taxes associated with your purchase.',
      'es':
          'El total de su pedido es un resumen de todos los artículos de su pedido menos las tarifas e impuestos asociados con su compra.',
      'ja': '注文合計は、注文に含まれる全商品の合計から購入に関連する手数料と税金を差し引いた金額です。',
      'pt':
          'O total do seu pedido é um resumo de todos os itens do seu pedido, menos quaisquer taxas e impostos associados à sua compra.',
      'zh_Hans': '您的订单总额是订单中所有商品的总和减去与您的购买相关的任何费用和税费。',
      'zh_Hant': '您的訂單總額是訂單中所有商品的匯總，減去與購買相關的任何費用和稅金。',
    },
    '9inlr4q7': {
      'en': 'Okay',
      'es': 'Bueno',
      'ja': 'わかった',
      'pt': 'OK',
      'zh_Hans': '好的',
      'zh_Hant': '好的',
    },
  },
  // changePhoto
  {
    'p0gi9q63': {
      'en': 'Change Profile Photo',
      'es': 'Cambiar foto de perfil',
      'ja': 'プロフィール写真の変更',
      'pt': 'Alterar foto do perfil',
      'zh_Hans': '更改个人资料照片',
      'zh_Hant': '更改個人資料照片',
    },
    'dq2tv8q6': {
      'en': 'Upload Photo',
      'es': 'Subir foto',
      'ja': '写真をアップロード',
      'pt': 'Carregar foto',
      'zh_Hans': '上传照片',
      'zh_Hant': '上傳照片',
    },
    'uau5505q': {
      'en': 'Save Photo',
      'es': 'Guardar foto',
      'ja': '写真を保存',
      'pt': 'Salvar foto',
      'zh_Hans': '保存照片',
      'zh_Hant': '保存照片',
    },
  },
  // reviewTrip
  {
    'rfvnvrx1': {
      'en': 'Rate Your Trip',
      'es': 'Califica tu viaje',
      'ja': '旅行を評価する',
      'pt': 'Avalie sua viagem',
      'zh_Hans': '评价您的旅程',
      'zh_Hant': '評價您的旅行',
    },
    'knqe2fby': {
      'en': 'Let us know what you thought of the place below!',
      'es': '¡Cuéntanos qué te pareció el lugar a continuación!',
      'ja': 'この場所についての感想を下記にお知らせください。',
      'pt': 'Conte-nos o que você achou do lugar abaixo!',
      'zh_Hans': '请让我们知道您对下面这个地方的看法！',
      'zh_Hant': '讓我們知道您對下面這個地方的看法！',
    },
    'wcij2rsr': {
      'en': 'How would you rate it?',
      'es': '¿Cómo lo calificarías?',
      'ja': 'どのように評価しますか?',
      'pt': 'Como você classificaria isso?',
      'zh_Hans': '您如何评价它？',
      'zh_Hant': '您如何評價它？',
    },
    'fgoh4y7h': {
      'en': 'Please leave a description of the place...',
      'es': 'Por favor deje una descripción del lugar...',
      'ja': '場所の説明を残してください...',
      'pt': 'Por favor, deixe uma descrição do lugar...',
      'zh_Hans': '请留下该地点的描述...',
      'zh_Hant': '請留下該地點的描述...',
    },
    '06edkvro': {
      'en': 'Submit Review',
      'es': 'Enviar reseña',
      'ja': 'レビューを送信',
      'pt': 'Enviar avaliação',
      'zh_Hans': '提交评论',
      'zh_Hant': '提交評論',
    },
  },
  // changeMainPhoto
  {
    'yphu5ihh': {
      'en': 'Change Main Photo',
      'es': 'Cambiar foto principal',
      'ja': 'メイン写真の変更',
      'pt': 'Alterar foto principal',
      'zh_Hans': '更改主照片',
      'zh_Hant': '更改主照片',
    },
    'ep8q4p3j': {
      'en': 'Upload Photo',
      'es': 'Subir foto',
      'ja': '写真をアップロード',
      'pt': 'Carregar foto',
      'zh_Hans': '上传照片',
      'zh_Hant': '上傳照片',
    },
    'jlbrrsal': {
      'en': 'Save Photo',
      'es': 'Guardar foto',
      'ja': '写真を保存',
      'pt': 'Salvar foto',
      'zh_Hans': '保存照片',
      'zh_Hant': '保存照片',
    },
  },
  // cancelTrip
  {
    '559pkr8k': {
      'en': 'Cancel Trip',
      'es': 'Cancelar viaje',
      'ja': '旅行をキャンセル',
      'pt': 'Cancelar viagem',
      'zh_Hans': '取消行程',
      'zh_Hant': '取消行程',
    },
    'jw9fncva': {
      'en':
          'If you want to cancel your tripl please leave a note below to send to the host.',
      'es':
          'Si desea cancelar su viaje, deje una nota a continuación para enviarla al anfitrión.',
      'ja': 'トリプルをキャンセルする場合は、以下にメモを残してホストに送信してください。',
      'pt':
          'Se você quiser cancelar sua viagem, deixe uma nota abaixo para enviar ao anfitrião.',
      'zh_Hans': '如果您想取消三人行，请在下面留言，发送给房东。',
      'zh_Hant': '如果您想取消行程，請在下面留言並發送給房東。',
    },
    'aqnamzjf': {
      'en': 'Your reason for cancelling...',
      'es': 'Su motivo de cancelación...',
      'ja': 'キャンセルの理由は…',
      'pt': 'O motivo do cancelamento...',
      'zh_Hans': '取消的原因...',
      'zh_Hant': '您取消的原因...',
    },
    '8obk9icq': {
      'en': 'Yes, Cancel Trip',
      'es': 'Sí, cancelar viaje',
      'ja': 'はい、旅行をキャンセルします',
      'pt': 'Sim, Cancelar Viagem',
      'zh_Hans': '是的，取消行程',
      'zh_Hant': '是的，取消行程',
    },
    '5g0yv1j6': {
      'en': 'Never Mind',
      'es': 'No importa',
      'ja': 'どうでも',
      'pt': 'Deixa para lá',
      'zh_Hans': '没关系',
      'zh_Hant': '沒關係',
    },
  },
  // cancelTripHOST
  {
    'ugob1zec': {
      'en': 'Cancel Trip',
      'es': 'Cancelar viaje',
      'ja': '旅行をキャンセル',
      'pt': 'Cancelar viagem',
      'zh_Hans': '取消行程',
      'zh_Hant': '取消行程',
    },
    'iof25vay': {
      'en':
          'If you want to cancel your tripl please leave a note below to send to the host.',
      'es':
          'Si desea cancelar su viaje, deje una nota a continuación para enviarla al anfitrión.',
      'ja': 'トリプルをキャンセルする場合は、以下にメモを残してホストに送信してください。',
      'pt':
          'Se você quiser cancelar sua viagem, deixe uma nota abaixo para enviar ao anfitrião.',
      'zh_Hans': '如果您想取消三人行，请在下面留言，发送给房东。',
      'zh_Hant': '如果您想取消行程，請在下面留言並發送給房東。',
    },
    'h86nuhcm': {
      'en': 'Your reason for cancelling...',
      'es': 'Su motivo de cancelación...',
      'ja': 'キャンセルの理由は…',
      'pt': 'O motivo do cancelamento...',
      'zh_Hans': '取消的原因...',
      'zh_Hant': '您取消的原因...',
    },
    '8dajscir': {
      'en': 'Yes, Cancel Trip',
      'es': 'Sí, cancelar viaje',
      'ja': 'はい、旅行をキャンセルします',
      'pt': 'Sim, Cancelar Viagem',
      'zh_Hans': '是的，取消行程',
      'zh_Hant': '是的，取消行程',
    },
    'zsi5990k': {
      'en': 'Never Mind',
      'es': 'No importa',
      'ja': 'どうでも',
      'pt': 'Deixa para lá',
      'zh_Hans': '没关系',
      'zh_Hant': '沒關係',
    },
  },
  // Miscellaneous
  {
    '0jhmeak8': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'giba54n1': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'q3o9qdwi': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '3uahyi1n': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '9ebo0yrq': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'lf51bp50': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ov2ku51f': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'a0b5llvd': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'wkol19c8': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'p7757yl8': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'u5cdcf9k': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'b0e7z5p1': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ejqmzc6t': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'tfhel1l3': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'j5si5s7i': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    '6ipz7g2c': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'xbaly1cz': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kjljlb4r': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'bk6hr7w9': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ffbb03zs': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'y3lg64ju': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'rivs55b7': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'w7i6bgnl': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'd2mukshs': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'ezofe7i6': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'twpobqyg': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
    'kc4i30e9': {
      'en': '',
      'es': '',
      'ja': '',
      'pt': '',
      'zh_Hans': '',
      'zh_Hant': '',
    },
  },
].reduce((a, b) => a..addAll(b));
